
DROP DATABASE userDb;

USE userDb;

CREATE DATABASE userDb;

CREATE TABLE users
(
	id INT NOT NULL AUTO_INCREMENT,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
  	createdAt  DATETIME,
    updatedAt DATETIME,
<<<<<<< HEAD
  	PRIMARY KEY( id )
);

CREATE TABLE posts
(
	id INT NOT NULL AUTO_INCREMENT,
	meal VARCHAR( 255 ) NOT NULL,
	createdAt DATETIME,
	votes INT,
  	PRIMARY KEY( id )
);
=======
  	PRIMARY KEY(id)
)
>>>>>>> b2a45a997974988e01ec81008375ca367375b645
